package com.example.flashcardsystent.data;

/**
 * Room entity representing a single flashcard.
 * Each comment in this file briefly explains the associated line.
 */

import androidx.room.Entity;       // denotes a table in the Room database
import androidx.room.ForeignKey;   // establishes relationship with Deck
import androidx.room.Index;        // index to speed up queries
import androidx.room.PrimaryKey;   // primary key annotation

@Entity(
        tableName = "Card", // table name
        foreignKeys = @ForeignKey( // relationship: each card belongs to a deck
                entity = Deck.class,
                parentColumns = "id", // id column in Deck
                childColumns = "deckId", // foreign key in this table
                onDelete = ForeignKey.CASCADE // delete cards if parent deck is removed
        ),
        indices = @Index("deckId") // create index for deckId column
)
public class Card {

    @PrimaryKey(autoGenerate = true) // unique id generated by Room
    public int id;

    public int deckId; // reference to the parent deck

    public String front; // text shown on the front side

    public String back; // text shown on the back side

    /**
     * Creates a new card with the given data.
     */
    public Card(int deckId, String front, String back) {
        this.deckId = deckId; // assign deck reference
        this.front = front;   // set front text
        this.back = back;     // set back text
    }

    /** Default constructor required by Room */
    public Card() {
    }
}