package com.example.flashcardsystent.data;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Entity storing the result of a completed classic flashcard session.
 * Includes performance statistics such as number of correct/incorrect answers,
 * the hardest card, and session timestamp.
 */
@Entity
public class ClassicResult {

    /** Unique ID for each result, auto-generated by Room */
    @PrimaryKey(autoGenerate = true)
    public int id;

    /** ID of the deck that was used during the session */
    public final int deckId;

    /** Number of cards the user marked as "known" */
    public final int correct;

    /** Number of cards the user marked as "unknown" */
    public final int wrong;

    /** Front side of the card that was most difficult during the session */
    public final String hardestCard;

    /** Time the session ended, represented in milliseconds since epoch */
    public final long timestamp;

    /**
     * Constructs a new ClassicResult entry with statistics.
     *
     * @param deckId       ID of the related deck
     * @param correct      number of correct responses
     * @param wrong        number of wrong responses
     * @param hardestCard  front text of the hardest card
     * @param timestamp    time the session was recorded
     */
    public ClassicResult(int deckId, int correct, int wrong, String hardestCard, long timestamp) {
        this.deckId = deckId;
        this.correct = correct;
        this.wrong = wrong;
        this.hardestCard = hardestCard;
        this.timestamp = timestamp;
    }
}
