package com.example.flashcardsystent.data;

/**
 * Room entity representing a set of flashcards.
 */

import androidx.room.Entity;    // marks class as Room table
import androidx.room.PrimaryKey; // indicates primary key field

@Entity
public class Deck {

    @PrimaryKey(autoGenerate = true) // unique id generated by Room
    public int id;

    public String name; // deck title

    public Deck(String name) {
        this.name = name; // set initial name
    }
}