package com.example.flashcardsystent.data;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Entity storing the result of a completed quiz session.
 * Includes counts of correct/wrong answers and metadata such as timestamp and total questions.
 */
@Entity
public class QuizResult {

    /** Unique identifier for each quiz result, auto-generated by Room */
    @PrimaryKey(autoGenerate = true)
    public int id;

    /** ID of the deck that was used in the quiz */
    public final int deckId;

    /** Number of correct answers during the quiz */
    public final int correct;

    /** Number of incorrect answers during the quiz */
    public int wrong;

    /** Total number of questions presented in the quiz */
    public final int total;

    /** Time when the quiz was completed, in milliseconds since epoch */
    public final long timestamp;

    /**
     * Constructs a new {@code QuizResult} with all statistics and metadata.
     *
     * @param deckId    the ID of the deck used in the quiz
     * @param correct   number of correctly answered questions
     * @param wrong     number of incorrect answers
     * @param total     total number of questions in the quiz
     * @param timestamp when the quiz was taken (epoch time)
     */
    public QuizResult(int deckId, int correct, int wrong, int total, long timestamp) {
        this.deckId = deckId;
        this.correct = correct;
        this.wrong = wrong;
        this.total = total;
        this.timestamp = timestamp;
    }
}
